import Prism from "prismjs";
import "prismjs/components/prism-markup-templating";
import "prismjs/components/prism-python";
import "prismjs/components/prism-typescript";
import "prismjs/components/prism-c";
import "prismjs/components/prism-cpp";
import "prismjs/components/prism-csharp";
import "prismjs/components/prism-java";
import "prismjs/components/prism-xml-doc";
import "prismjs/components/prism-json";
import "prismjs/components/prism-php";
import "prismjs/components/prism-jsx";
import "prismjs/components/prism-maxscript";
import "prismjs/components/prism-applescript";
import "prismjs/components/prism-bash";
import "prismjs/components/prism-ruby";
import "prismjs/components/prism-objectivec";
import "prismjs/components/prism-swift";
import "prismjs/components/prism-dart";
import "prismjs/components/prism-kotlin";
import "prismjs/components/prism-sql";
import "prismjs/components/prism-mongodb";
import "prismjs/components/prism-yaml";
import "prismjs/components/prism-go";
import "prismjs/components/prism-go-module";
import "prismjs/components/prism-django";
import "prismjs/components/prism-jq";
import "prismjs/components/prism-r";
import "prismjs/components/prism-aspnet";
import "prismjs/components/prism-powershell";
import "prismjs/components/prism-docker";

export default Prism;
